---
# User vars
app_user_home_path: /home/swenvp1

users:
  - name: swenvp1
    group: swenvp1

staffware_directory: /app/iProcess/11_8

ansible_deploy_playbook_directory: "/root"

postfix_main_config_file: main.cf
postfix_config:
  - key: mydomain
    value: default.local
  - key: myorigin 
    value: $mydomain
  - key: relayhost
    value: myrelay.local

postfix_net_config:
  - key: inet_interfaces 
    value: all
  - key: inet_protocols 
    value: ipv4