---

update_os: true

## Add any additional packages
additional_packages:
  - postfix
  - jq
 
additional_packages_pip:
  - name: pip
    state: latest
  - name: ansible
    version: "2.10.6"
  - name: j2cli
    umask: "0022"

# Selinux setup
selinux_status:
  - policy: targeted
    state: permissive

# User vars
app_user_home_path: /home/swenvp1

users:
  - name: swenvp1

## NFS Options
install_watcher_service: false

## Postfix Outbound email
postfix_main_config_file: main.cf
postfix_config:
  - key: mydomain
    value: companieshouse.gov.uk
  - key: myorigin
    value: $mydomain
  - key: relayhost
    value: smtp-outbound.sharedservices.aws.internal

postfix_net_config:
  - key: inet_interfaces
    value: all
  - key: inet_protocols
    value: ipv4

csi_folder_s3_prefix: iprocess-configs/csi-folder/
csi_folder_local_path: /app/iProcess/11_8/csi
swadmin_crontab_user: swadmin
swadmin_crontab_file: crontab-swadmin.txt
swadmin_crontab_dir: /app/iProcess/11_8/csi