Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define "iprocess-app"
  config.vm.provider "virtualbox" do |v|
    #Needs a reasonable RAM allocation or ClamAV daemon fails first time start
    v.memory = 4096 
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf update
    sudo dnf install python38
    python3 -m pip install --upgrade pip --user
    python3 -m pip  install ansible --user
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    # ansible.verbose = "vvv"
  end
end
