Vagrant.configure("2") do |config|
  # config.vm.box = "elastic/rhel-8-x86_64"
  # config.vm.box = "generic/rhel8"
  config.vm.box = "centos/8"
  config.vm.define "iprocess-app"
  config.vm.provider "virtualbox" do |v|
    #Needs a reasonable RAM allocation or ClamAV daemon fails first time start
    v.memory = 4096 
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
